### ISSUE TITLE
`make install-pip-package` error: CMake Error: GAPartNet_env/Open3D/python/js/lib/web_visualizer.js does not exist

### ISSUE THREAD

**Issue by dadadadawjb** [geng-haoran/GAPartNet_env#1]
Hi, 

when building and installing open3d with pytorch extension, I encountered a problem running the command `make install-pip-package`. It successfully built 100% targets but failed in installing, throwing `CMake Error: GAPartNet_env/Open3D/python/js/lib/web_visualizer.js does not exist`, by `configure_file` in `GAPartNet_env/Open3D/cpp/pybind/make_python_package.cmake:L55`. Is this file necessary? Can I just comment this `configure_file`?

**Comment by geng-haoran** [comment]
There are some files ignored in the repo. Please install the original Open3D repo. I updated the installation instruction just now. Please check it! Thank you for the helpful issue. If you have any further questions, feel free to contact me!

**Comment by dadadadawjb** [comment]
Hi @geng-haoran , thanks for the amazing work and updating!

BTW, is open3d with pytorch extension built from source necessary for [PartManip](https://github.com/PKU-EPIC/PartManip)? Can I just install the pre-built release by just `pip install open3d`? I tried it and no errors were thrown.

**Comment by geng-haoran** [comment]
the extension is used for Part Segmentation, so it is not necessary for the released version of PartManip~

**Comment by dadadadawjb** [comment]
Get it! Thanks for the details!
